//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewOptics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewOptics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AchatsProduits {
            get {
                object obj = ResourceManager.GetObject("AchatsProduits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BonDeLivraisonDemi {
            get {
                object obj = ResourceManager.GetObject("BonDeLivraisonDemi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BonDeLivraisonDemiTunisie {
            get {
                object obj = ResourceManager.GetObject("BonDeLivraisonDemiTunisie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dessin {
            get {
                object obj = ResourceManager.GetObject("dessin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestockageProduit {
            get {
                object obj = ResourceManager.GetObject("DestockageProduit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Etat104Report {
            get {
                object obj = ResourceManager.GetObject("Etat104Report", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EtatClientVersement {
            get {
                object obj = ResourceManager.GetObject("EtatClientVersement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExamenBinoculaire {
            get {
                object obj = ResourceManager.GetObject("ExamenBinoculaire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExamenOpto {
            get {
                object obj = ResourceManager.GetObject("ExamenOpto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream facebookme_lZ4iKc6J {
            get {
                return ResourceManager.GetStream("facebookme_lZ4iKc6J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Facture {
            get {
                object obj = ResourceManager.GetObject("Facture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FactureSansTva {
            get {
                object obj = ResourceManager.GetObject("FactureSansTva", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FactureTunisienne {
            get {
                object obj = ResourceManager.GetObject("FactureTunisienne", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FamilleProduit {
            get {
                object obj = ResourceManager.GetObject("FamilleProduit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FicheAtelierLentille {
            get {
                object obj = ResourceManager.GetObject("FicheAtelierLentille", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FicheAtelierMonture {
            get {
                object obj = ResourceManager.GetObject("FicheAtelierMonture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FicheAtelierMontureDouble {
            get {
                object obj = ResourceManager.GetObject("FicheAtelierMontureDouble", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HistoriqueAchat {
            get {
                object obj = ResourceManager.GetObject("HistoriqueAchat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ImpressionFicheAtelierMontureRecu {
            get {
                object obj = ResourceManager.GetObject("ImpressionFicheAtelierMontureRecu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ImpressionVersments {
            get {
                object obj = ResourceManager.GetObject("ImpressionVersments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LentilleDouble {
            get {
                object obj = ResourceManager.GetObject("LentilleDouble", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LentilleRecu {
            get {
                object obj = ResourceManager.GetObject("LentilleRecu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ListeClients {
            get {
                object obj = ResourceManager.GetObject("ListeClients", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ListeCommande {
            get {
                object obj = ResourceManager.GetObject("ListeCommande", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ListeDesAchats {
            get {
                object obj = ResourceManager.GetObject("ListeDesAchats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ListeStockAlere {
            get {
                object obj = ResourceManager.GetObject("ListeStockAlere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewOptics.
        /// </summary>
        internal static string Logiciel {
            get {
                return ResourceManager.GetString("Logiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MarqueProduit {
            get {
                object obj = ResourceManager.GetObject("MarqueProduit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cette écriture est générer automatiquement! vous ne pouvez pas la supprimer dans ce module.
        /// </summary>
        internal static string MessageBoxEcriutreautomatique {
            get {
                return ResourceManager.GetString("MessageBoxEcriutreautomatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas le droit d&apos;accéder a ce module.
        /// </summary>
        internal static string MessageBoxPrivilége {
            get {
                return ResourceManager.GetString("MessageBoxPrivilége", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmez cette opération.
        /// </summary>
        internal static string MessageBoxQuestionOperation {
            get {
                return ResourceManager.GetString("MessageBoxQuestionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MouvementCaisse {
            get {
                object obj = ResourceManager.GetObject("MouvementCaisse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NomenclatureProduit {
            get {
                object obj = ResourceManager.GetObject("NomenclatureProduit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OneFactureAchat {
            get {
                object obj = ResourceManager.GetObject("OneFactureAchat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération a été annulée.
        /// </summary>
        internal static string Opérationéchouée {
            get {
                return ResourceManager.GetString("Opérationéchouée", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération a été annulée , la transaction a échoué.
        /// </summary>
        internal static string OpérationéchouéeTransaction {
            get {
                return ResourceManager.GetString("OpérationéchouéeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération terminée avec succès.
        /// </summary>
        internal static string OperationSuccées {
            get {
                return ResourceManager.GetString("OperationSuccées", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Peremption {
            get {
                object obj = ResourceManager.GetObject("Peremption", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RecuDePaiement {
            get {
                object obj = ResourceManager.GetObject("RecuDePaiement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReglementPatient {
            get {
                object obj = ResourceManager.GetObject("ReglementPatient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportAMS {
            get {
                object obj = ResourceManager.GetObject("ReportAMS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportCaisse {
            get {
                object obj = ResourceManager.GetObject("ReportCaisse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportCreditFournisseur {
            get {
                object obj = ResourceManager.GetObject("ReportCreditFournisseur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportFourn {
            get {
                object obj = ResourceManager.GetObject("ReportFourn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportListeCatalogueLentille {
            get {
                object obj = ResourceManager.GetObject("ReportListeCatalogueLentille", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportListeCatalogueVerre {
            get {
                object obj = ResourceManager.GetObject("ReportListeCatalogueVerre", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOneClient {
            get {
                object obj = ResourceManager.GetObject("ReportOneClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportOneSupp {
            get {
                object obj = ResourceManager.GetObject("ReportOneSupp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportProduit {
            get {
                object obj = ResourceManager.GetObject("ReportProduit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReportSupplement {
            get {
                object obj = ResourceManager.GetObject("ReportSupplement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.medicalogitech.com.
        /// </summary>
        internal static string SiteWeb {
            get {
                return ResourceManager.GetString("SiteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StockReport {
            get {
                object obj = ResourceManager.GetObject("StockReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TableauDeBord {
            get {
                object obj = ResourceManager.GetObject("TableauDeBord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ticket {
            get {
                object obj = ResourceManager.GetObject("Ticket", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VenteF1rdlc {
            get {
                object obj = ResourceManager.GetObject("VenteF1rdlc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VersementClient {
            get {
                object obj = ResourceManager.GetObject("VersementClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
